apiVersion: v1
kind: Service
metadata:
  name: mi-crud-service
  namespace: mi-aplicacion
spec:
  type: NodePort
  selector:
    app: mi-crud-app-reto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30080
